### ISSUE TITLE
Add support for 3-digit hex words and 'R'

### ISSUE THREAD

**Issue by jc65536** [paoloricciuti/hexwords#1]
Here is a list of 3-digit hex codes and their matching words, as well as words that map 'R' to "12". Could you please add them to your site?

[zipped.txt](https://github.com/paoloricciuti/hexwords/files/8864127/zipped.txt)

**Comment by paoloricciuti** [comment]
I really don't like the R mapping but i would add 3 words letter as soon as i can

**Comment by paoloricciuti** [comment]
I've added the three and four letters color in the last release, thanks for the feedback
