### ISSUE TITLE
Doesnt work with Firefox

### ISSUE THREAD

**Issue by 89z** [paoloricciuti/hexwords#2]
![fail](http://0x0.st/oMvf.png)

**Comment by paoloricciuti** [comment]
What version of firefox are you in?

**Comment by 89z** [comment]
88

**Comment by paoloricciuti** [comment]
Uh i tought svelte-kit would autoprefix those...i'll fix it ASAP

**Comment by 89z** [comment]
I think it would be better to just not use `fit-content` to begin with. The default value for `width` is `auto`, which seems to work fine in this case. So why even use a custom value, let alone an experimental one?

**Comment by paoloricciuti** [comment]
Yeah i swapped to auto in the new commit....closing this
